var MSG = {
  catInOut:"إرسال و إستقبال",
  catDigital:"الرقمي",
  catAnalog:"التماثلي",
  catSerial:"التسلسل",
  catSoftSerial:"التسلل البرمجي",
  catServo:"المحركات",
  catSerialLCD:"شاشة العرض البلوري السائل",
  catString:"سلسلة حروف",
  catDivers:"مقاطع مختلفة",
  title: "برمجة أردوينو",
  blocks: "المقاطع البرمجية",
  linkTooltip: "احفظ ووصلة إلى المقاطع البرمجية.",
  runTooltip: "شغل البرنامج المعرف بواسطة البلوكات في مساحة العمل.",
  badCode: "خطأ في البرنامج:\n %1",
  timeout: "تم تجاوز الحد الأقصى لتكرارات التنفيذ .",
  discard: "حذف كل بلوكات %1؟",
  trashTooltip: "تجاهل كل البلوكات.",
  catLogic: "منطق",
  catConversion:"تحويل",
  catAdvanced:"المداخل و المخارج المتقدمة",
  catLoops: "الحلقات",
  catMath: "رياضيات",
  catText: "نص",
  catLists: "قوائم",
  catColour: "لون",
  catVariables: "متغيرات",
  catFunctions: "إجراءات",
  listVariable: "قائمة",
  textVariable: "نص",
  httpRequestError: "كانت هناك مشكلة مع هذا الطلب.",
  linkAlert: "مشاركة كود بلوكلي الخاص بك مع هذا الرابط:\n %1",
  hashError: "عذراً،ال '%1' لا تتوافق مع أي برنامج تم حفظه.",
  xmlError: "تعذر تحميل الملف المحفوظة الخاصة بك.  ربما تم إنشاؤه باستخدام إصدار مختلف من بلوكلي؟",
  badXml: "خطأ في توزيع ال \"XML\":\n %1\n\nحدد 'موافق' للتخلي عن التغييرات أو 'إلغاء الأمر' لمواصلة تحرير ال\"XML\".",
  warningBadBlock:"لم يتم توصيل هذه الكتلة بشكل صحيح إلى الكتل الأخرى",
  warningPleaseFix:"يرجى تصحيح  هذه الكتلة"
};
