var MSG = {
  catInOut:"IN/OUT",
  catDigital:"Digitales",
  catAnalog:"Analogicas",
  catSerial:"Serial",
  catSoftSerial:"SoftwareSerial",
  catServo:"Servo",
  catSerialLCD:"LCD serial",
  catString:"Cadena",
  catDivers:"Drivers",
  title: "CODIGO",
  blocks: "BLOQUES",
  linkTooltip: "Guardar y unir los bloques.",
  runTooltip: "Lanzamiento del programa definido por los bloques en el área de trabajo.",
  badCode: "Error de programa :\n%1",
  timeout: "Ejecución máxima de iteraciones excedido.",
  discard: "Retire todos %1 bloques?",
  trashTooltip: "Deseche todos los bloques.",
  catLogic: "Lógica",
  catConversion:"Conversion",
  catAdvanced:"E/S Avanzada",
  catSerial:"Serial",
  catLoops: "Ciclos",
  catMath: "Matematicas",
  catText: "Texto",
  catLists: "Listas",
  catColour: "Color",
  catVariables: "Variables",
  catFunctions: "Funciones",
  listVariable: "Lista",
  textVariable: "Texto",
  httpRequestError: "Hubo un problema con la aplicación.",
  linkAlert: "Compartir sus bloques a través de este enlace:\n\n%1",
  hashError: "Lo siento, '%1' no coincide con ningún programa guardado.",
  xmlError: "No se puede cargar el archivo de copia de seguridad. Tal vez se ha creado con otra versión de Blockly?",
  badXml: "Error analisis de XML :\n%1\n\nSeleccione 'OK' para descartar los cambios 'Annuler' para continuar editando el XML.",
  warningBadBlock:"Este bloque no está conectado a otros bloques.",
  warningPleaseFix:"Por favor, corrija la advertencia en este bloque."
};
